### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pygone** [ywang-wnlo/HustNetwork#1]
是否可以基于你的代码, 做一个带界面的程序, 方便使用呢

**Comment by ywang-wnlo** [comment]
欢迎你二次开发~
不过正常来说 Linux 环境下配置成 service 已经足够无感了
Windows 的话可能确实打包成 exe 较好，有空的话我再尝试下

**Comment by Pygone** [comment]
主要方向是做一个Windows下带Qt界面的程序, 面向更大的群体

**Comment by ywang-wnlo** [comment]
做个了 demo，大致这样？？？

![demo](https://user-images.githubusercontent.com/10515578/202367572-ee9ccc77-3bdb-47af-86da-c15e949a494f.png)

**Comment by EI233** [comment]
＜（＾－＾）＞

**Comment by Pygone** [comment]
对

**Comment by ywang-wnlo** [comment]
打包了一个版本，可以试试看
