### ISSUE TITLE
重连报错

### ISSUE THREAD

**Issue by Xiong5Heng** [ywang-wnlo/HustNetwork#11]
你好！我将脚本配置成service一直挂在后台，昨天不能重连了，今天发现log中出现下面这种错误，请问如何解决
[2023-11-25 09:04:51] 锐捷掉线，尝试重连 fail 登录密码必须加密！

**Comment by ywang-wnlo** [comment]
可能是学校升级了认证流程，后续我看下~

**Comment by ywang-wnlo** [comment]
已修复
