### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by Cnhhc** [ywang-wnlo/HustNetwork#2]
用了v0.4版本几天，发现了一个bug，就是每天启动软件的时候，软件都会在C:\Users\ccc\AppData\Local\Temp目录下创建一个名为_MEI56842（其中数字为随机编号），一个文件差不多60M，其中最大的子文件为PySide6，差不多54M，感觉是工具的开发环境（我本人不是计算机专业的，很多技术细节不懂，但显然这些文件是重复的）。这个文件每次启动软件都会被创建，还是挺浪费C盘空间的，能否修复这个bug？
![image](https://user-images.githubusercontent.com/42515010/205441630-4b9d533e-4a94-4079-bf20-ca64fd99cda6.png)
![image](https://user-images.githubusercontent.com/42515010/205441663-872d9016-073a-476a-9996-41372782725e.png)

**Comment by ywang-wnlo** [comment]
请问你这是每次都强制关闭程序的吗？按照正常程序退出时，其实会自动删除该文件夹下的内容的

https://pyinstaller.org/en/stable/operating-mode.html#how-the-one-file-program-works

> The _MEIxxxxxx folder is not removed if the program crashes or is killed (kill -9 on Unix, killed by the Task Manager on Windows, “Force Quit” on macOS). Thus if your app crashes frequently, your users will lose disk space to multiple _MEIxxxxxx temporary folders.

**Comment by Cnhhc** [comment]
是的，在托盘模式下，一般不会手动去退出，一般直接关机了

**Comment by Cnhhc** [comment]
像向日葵，校园网这些隐藏在系统托盘的程序，用户还是习惯直接关机，很少会主动去关闭

**Comment by ywang-wnlo** [comment]
嗯嗯，我知道，我看看怎么修复比较好

**Comment by Cnhhc** [comment]
问个题外话，这个程序后续还有开发计划吗，还是主体功能已经完成了，后续以修补bug为主

**Comment by ywang-wnlo** [comment]
目前来说没必要增加其他功能了吧23333（主要是自己不常用，所以一时半会也想不到啥新功能

**Comment by Cnhhc** [comment]
ok，我这边主要是给工作站用的，工作站连校园网经常掉线，远程控制失效，至于功能，我建议加一个校园网下线的功能（有时测试网络的时候需要这个功能），这样就能完全替代锐捷客户端了，最后还是非常感谢开发这个工具，辛苦了

**Comment by ywang-wnlo** [comment]
校园网下线是指把该机器的认证取消吗？还是说支持同账号的所有设备下线？

**Comment by Cnhhc** [comment]
把当前设备校园网认证取消，其他设备不影响，也就是手动断网，锐捷有这个功能

**Comment by ywang-wnlo** [comment]
ok 后期应该会加上（挖坑

**Comment by Cnhhc** [comment]
感谢！！！！！

**Comment by ywang-wnlo** [comment]
Fixed!
https://github.com/ywang-wnlo/HustNetwork/releases/tag/v0.5

**Comment by Cnhhc** [comment]
ok

**Comment by Cnhhc** [comment]
![image](https://user-images.githubusercontent.com/42515010/205446173-395ca904-4efd-4070-89c7-484b60764c25.png)
bug......

**Comment by ywang-wnlo** [comment]
Fixed...
