### ISSUE TITLE
断线重连的尝试次数

### ISSUE THREAD

**Issue by Cnhhc** [ywang-wnlo/HustNetwork#3]
请问这个断线重连的尝试次数是有限的吗?
1.6号那次校园网升级，从1.6晚上10点到次日凌晨3点校园网中断，我们办公室所有的主机都下线了，断线重连程序没有执行。
所以我怀疑是不是这个程序重连只会执行有限次数，如果校园网中断时间过长，重连次数执行完之后，就不会重连了

**Comment by ywang-wnlo** [comment]
并没有次数限制，但是完全断网（类似电脑没插网线）情况下，重连程序可能会报错退出

不过我现在没有校园网测试环境，后面可能会上 `try` 语句保证不会因为这种异常导致失败

**Comment by Cnhhc** [comment]
ok
